name: NeuralLift
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - cudatoolkit=12.6
  - pytorch>=2.1.0
  - torchvision>=0.16.0
  - torchaudio>=2.1.0
  - numpy
  - scipy
  - pandas
  - matplotlib
  - tqdm
  - tensorboard
  - tensorboardX
  - scikit-learn
  - accelerate
  - rich
  - opencv-python-headless
  - ninja
  - PyMCubes
  - xatlas
  - dearpygui
  - transformers
  - diffusers
  - huggingface_hub
  - kornia
  - pip:
    - absl-py
    - accelerate
    - addict
    - albumentations
    - antlr4-python3-runtime
    - aiosignal
    - altair
    - anyio
    - basicsr
    - beautifulsoup4
    - blis
    - cachetools
    - catalogue
    - charset-normalizer
    - cmake>=3.22
    - contourpy
    - cycler
    - datasets
    - decord
    - diffusers
    - dill
    - einops
    - ffmpy
    - filelock
    - flask
    - flatbuffers
    - fonttools
    - fsspec
    - ftfy
    - future
    - gdown
    - gitpython
    - gradio>=3.24.1
    - huggingface-hub
    - hydra-core
    - imageio
    - imageio-ffmpeg
    - imgaug
    - iopath
    - ipython
    - itsdangerous
    - jinja2
    - joblib
    - jsonschema
    - kornia
    - matplotlib-inline
    - mediapipe
    - networkx
    - numba
    - open-clip-torch
    - opencv-contrib-python
    - opencv-python-headless
    - orjson
    - pathtools
    - pillow
    - plotly
    - protobuf
    - psutil
    - pycocotools
    - pydantic
    - pyrallis
    - pytorch-lightning
    - regex
    - requests
    - safetensors
    - sentencepiece
    - setuptools
    - shapely
    - shortuuid
    - soupsieve
    - spacy
    - sympy
    - tensorboard
    - tensorboardx
    - text-unidecode
    - timm
    - tokenizers
    - torchmetrics
    - tqdm
    - transformers
    - wandb
    - websockets
    - xatlas
    - yapf
